#!/bin/bash
# Apply unitheme to Waybar by regenerating the palette CSS file.
# waybar/style.css imports this file, so colors update automatically.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/theme.conf"

MACCHIATO_CSS="${HOME}/.config/waybar/macchiato.css"

if [[ ! -d "$(dirname "$MACCHIATO_CSS")" ]]; then
    echo "Waybar config directory not found"
    exit 1
fi

cat > "$MACCHIATO_CSS" << EOF
/*
 * Generated by unitheme — edit ${SCRIPT_DIR}/theme.conf to change colors.
 */

@define-color base      ${COLOR_BASE};
@define-color mantle    ${COLOR_MANTLE};
@define-color crust     ${COLOR_CRUST};

@define-color text      ${COLOR_TEXT};
@define-color subtext0  ${COLOR_SUBTEXT0};
@define-color subtext1  ${COLOR_SUBTEXT1};

@define-color surface0  ${COLOR_SURFACE0};
@define-color surface1  ${COLOR_SURFACE1};
@define-color surface2  ${COLOR_SURFACE2};

@define-color overlay0  ${COLOR_OVERLAY0};
@define-color overlay1  ${COLOR_OVERLAY1};
@define-color overlay2  ${COLOR_OVERLAY2};

@define-color blue      ${COLOR_BLUE};
@define-color lavender  ${COLOR_LAVENDER};
@define-color sapphire  ${COLOR_SAPPHIRE};
@define-color sky       ${COLOR_SKY};
@define-color teal      ${COLOR_TEAL};
@define-color green     ${COLOR_GREEN};
@define-color yellow    ${COLOR_YELLOW};
@define-color peach     ${COLOR_PEACH};
@define-color maroon    ${COLOR_MAROON};
@define-color red       ${COLOR_RED};
@define-color mauve     ${COLOR_MAUVE};
@define-color pink      ${COLOR_PINK};
@define-color flamingo  ${COLOR_FLAMINGO};
@define-color rosewater ${COLOR_ROSEWATER};
EOF

echo "Applied theme to Waybar"

# Reload Waybar if running
if pgrep -x waybar &>/dev/null; then
    pkill -SIGUSR2 waybar && echo "Reloaded Waybar"
fi
